version: 0.2

phases:
  build:
    commands:
      - cd app
      - npm install
      - npm run build
      - aws s3 cp app/build/ s3://cognito.dbroadhurst.net/ --recursive --acl public-read

artifacts:
  files:
    app/build/**/*
  